spring:
  application:
    name: customer-service
  profiles:
    active: customer_service
  config:
    import: 'configserver:'
  cloud:
    config:
      name: customer-service,config-client
      uri: http://localhost:8888
      username: twitter-demo-cloud-server
      password: '{cipher}83f191bc8e178b2fdbcfc076d2c45ed972ab961473f37f6ff10fdd3b576fe82d37055739c114074205971fd9c962a176'

