object Dependencies {
    const val SPRING_BOOT_STARTER = "org.springframework.boot:spring-boot-starter:${Versions.SPRING_BOOT}"
    const val SPRING_BOOT_STARTER_LOGGING = "org.springframework.boot:spring-boot-starter-logging:${Versions.SPRING_BOOT}"
    const val SPRING_BOOT_STARTER_TEST = "org.springframework.boot:spring-boot-starter-test:${Versions.SPRING_BOOT}"
    const val SPRING_BOOT_STARTER_JSON = "org.springframework.boot:spring-boot-starter-json:${Versions.SPRING_BOOT}"
    const val SPRING_BOOT_STARTER_DATA_JPA = "org.springframework.boot:spring-boot-starter-data-jpa:${Versions.SPRING_BOOT}"
    const val SPRING_BOOT_STARTER_WEB = "org.springframework.boot:spring-boot-starter-web:${Versions.SPRING_BOOT}"
    const val SPRING_BOOT_STARTER_SECURITY = "org.springframework.boot:spring-boot-starter-security:${Versions.SPRING_BOOT}"
    const val SPRING_BOOT_STARTER_VALIDATION = "org.springframework.boot:spring-boot-starter-validation:${Versions.SPRING_BOOT}"
    const val SPRING_AUTOCONFIGURE = "org.springframework.boot:spring-boot-autoconfigure:${Versions.SPRING_BOOT}"

    const val SPRING_TX = "org.springframework:spring-tx:${Versions.SPRING_TX}"
    const val SPRING_KAFKA = "org.springframework.kafka:spring-kafka:${Versions.SPRING_KAFKA}"
    const val SPRING_CLOUD_CONFIG_SERVER = "org.springframework.cloud:spring-cloud-config-server:${Versions.SPRING_CLOUD}"
    const val SPRING_CLOUD_STARTER_CONFIG = "org.springframework.cloud:spring-cloud-starter-config:${Versions.SPRING_CLOUD}"

    const val KOTLIN_REFLECT = "org.jetbrains.kotlin:kotlin-reflect:${Versions.KOTLIN}"
    const val JACKSON_MODULE_KOTLIN = "com.fasterxml.jackson.module:jackson-module-kotlin:${Versions.JACKSON_KOTLIN}"
    const val LOMBOK = "org.projectlombok:lombok:${Versions.LOMBOK}"
    const val JUNIT_JUPITER = "org.junit.jupiter:junit-jupiter:${Versions.JUNIT_JUPITER}"
    const val JUNIT_PLATFORM_LAUNCHER = "org.junit.platform:junit-platform-launcher"
    const val MOKITO_KOTLIN = "org.mockito.kotlin:mockito-kotlin:${Versions.MOKITO_KOTLIN}"
    const val COMMON_TEXT = "org.apache.commons:commons-text:${Versions.COMMON_TEXT}"
    const val KOTLIN_TEST = "org.jetbrains.kotlin:kotlin-test"
    const val POSTGRESQL = "org.postgresql:postgresql:${Versions.POSTGRESQL}"
    const val KAFKA_AVRO_SERIALIZER = "io.confluent:kafka-avro-serializer:${Versions.KAFKA_AVRO_SERIALIZER}"
    const val KOTLIN_GRADLE_PLUGIN = "org.jetbrains.kotlin:kotlin-gradle-plugin:${Versions.KOTLIN}"
}