/*
 * This file was generated by the Gradle 'init' task.
 */

// Apply the common convention plugin for shared build configuration between library and application projects.
apply<CommonConventionsPlugin>()

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}
